# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pno < Formula
  desc "Generate and validate a Swedish Personnummer, an individualized identifier assigned to each individual born in Sweden"
  homepage "https://github.com/dominikwinter/pno"
  version "1.4.1"
  license "MIT"

  on_macos do
    url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_darwin_all.tar.gz"
    sha256 "ca8b6262588b21d03c5958ff5b4fbe109be89ccca4da12ce29dd4cabf836c4f8"

    def install
      bin.install "pno"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_linux_arm64.tar.gz"
      sha256 "69091acc1cfffee3839039ae2d85ef7f7d4536534073c813a95bdc7287ae2d64"

      def install
        bin.install "pno"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_linux_amd64.tar.gz"
      sha256 "04678324219a833bdd4eb27fb94894760148c684c0090f4f8a8aae0857f1ceed"

      def install
        bin.install "pno"
      end
    end
  end
end
