# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pno < Formula
  desc ""
  homepage "https://github.com/dominikwinter/pno"
  version "1.4.1"
  license "MIT"

  on_macos do
    url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_darwin_all.tar.gz"
    sha256 "3b4901184a7e6845032a20a2b53fa9550e6f0e609336c6a12cea60f1f03e93ea"

    def install
      bin.install "pno"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_linux_amd64.tar.gz"
      sha256 "ef9ab9b254e3ad8c7e28d977e38a6b4d9a82340669108813eaa44b9e8920ff94"

      def install
        bin.install "pno"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_linux_arm64.tar.gz"
      sha256 "1fd40f4fae4d25259f1c24a6d57281534f7fb15f0eadd805d55ca1edfaf82d1b"

      def install
        bin.install "pno"
      end
    end
  end
end
