# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pno < Formula
  desc "Generate and validate a Swedish "Personnummer," an individualized identifier assigned to each individual born in Sweden"
  homepage "https://github.com/dominikwinter/pno"
  version "1.4.1"
  license "MIT"

  on_macos do
    url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_darwin_all.tar.gz"
    sha256 "50627cc66a68bcece04fdc5e204a4a1cde18569c39ad12b7b2b26e486ffc8221"

    def install
      bin.install "pno"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_linux_arm64.tar.gz"
      sha256 "3e5161449226b5813c2d7f813c8e670ca02816a8e942c8735f7ed0e3636420a4"

      def install
        bin.install "pno"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dominikwinter/pno/releases/download/v1.4.1/pno_1.4.1_linux_amd64.tar.gz"
      sha256 "e36e6e39d90d7ae22761b827c751ba1607047c8d83bdcb6860f1ef8b712121aa"

      def install
        bin.install "pno"
      end
    end
  end
end
